import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/layout/Header'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import logo from '../assets/brittanyscraftbox.jpg'
import frontBanner from '../assets/atfarmersmarket3.jpg'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Header/>
      <main >
        <Container>
        <Row>
          <Col md={12}>
            <Image src={logo} />
           </Col>
        </Row>
          <Row>
          <Col md={12}>
          <h1>Brittany's Craft Box</h1>

          </Col>
        </Row>
        <Row>
          <Col md={12}>
          <p>The perfect place for any and all custom craft creations! Whether you're looking for something scary for Halloween or something sweet for that special someone on Valentine's Day, we've got you covered.</p>

          </Col>
        </Row>
        <Row>
          <Col md={12}>
          <p>Check out a sample of our latest crafts and creations. If you don't see exactly what you're looking for, it doesn't mean we don't have it or can't make it. Reach out to us about custom crafted products made just for YOU!</p>

          </Col>

        </Row>
        <Row className={styles.frontbanner}>
          <Col md={12} >
           
           </Col>
        </Row>
        
        </Container>
      </main>
      <br/>
      <br/>   
    </>
  )
}
